language: python
python:
  - "2.6"
before_script:
  - flake8 bedrock lib
  - mysql -e 'create database bedrock_test;'
  - python manage.py syncdb --noinput --migrate
  - python manage.py update_product_details
  - svn checkout https://svn.mozilla.org/projects/mozilla.com/trunk/locales/ locale
script: coverage run manage.py test
before_install:
  - git submodule update --init --recursive
install:
  - pip install -r requirements/dev.txt
after_success:
  # Report coverage results to coveralls.io
  - pip install coveralls
  - coveralls
notifications:
  irc:
    channels:
      - "irc.mozilla.org#www"
    on_success: change
    on_failure: always
    use_notice: true
